import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'

const inter = Montserrat({
  subsets: ['latin'],
  weight: ['400', '600', '500', '700', '800', '900'],
})

export const metadata: Metadata = {
  title: 'ULC Terminal',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
